-- init.sql
-- Extensiones necesarias
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS departamentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ciudades (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  departamento_id integer NOT NULL,
  nombre varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nombres varchar(150),
  primer_apellido varchar(80),
  segundo_apellido varchar(80),
  tipo_identificacion varchar(10),
  identificacion varchar(30) UNIQUE,
  email varchar(255) UNIQUE,
  telefono varchar(30), -- ✅ ya NO es UNIQUE
  genero varchar(20),
  password_hash varchar(255),
  ciudad_id integer,
  status varchar(20) DEFAULT 'PENDING',
  email_verificado boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code varchar(30) UNIQUE,
  name varchar(80)
);

CREATE TABLE IF NOT EXISTS usuario_roles (
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS verificaciones_otp (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  code_hash varchar(255),
  tipo varchar(20),
  status varchar(20) DEFAULT 'PENDING', -- ✅ nuevo: PENDING/VERIFIED/EXPIRED
  expires_at timestamptz,
  used_at timestamptz
);

-- (Opcional pero recomendado) Validación de valores permitidos para status
ALTER TABLE verificaciones_otp
  ADD CONSTRAINT chk_otp_status
  CHECK (status IN ('PENDING', 'VERIFIED', 'EXPIRED'));

CREATE TABLE IF NOT EXISTS bancos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS documentos_s3 (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  banco_id integer,
  s3_key text,
  original_filename varchar(255),
  file_size bigint,
  mime_type varchar(50),
  pdf_encrypted boolean DEFAULT false,
  checksum_sha256 varchar(64),
  status varchar(20) DEFAULT 'UPLOADED',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS analisis_hipotecario (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  documento_id uuid NOT NULL,
  ingresos_mensuales numeric(15,2),
  capacidad_pago_max numeric(15,2),
  tipo_contrato_laboral varchar(80),
  numero_credito varchar(50),
  sistema_amortizacion varchar(20),
  valor_prestado_inicial numeric(15,2),
  fecha_desembolso date,
  cuotas_pactadas integer,
  cuotas_pagadas integer,
  cuotas_pendientes integer,
  valor_cuota_actual numeric(15,2),
  beneficio_frech_mensual numeric(15,2),
  saldo_capital_hoy numeric(15,2),
  ajuste_inflacion_pesos numeric(15,2),
  intereses_mes_actual numeric(15,2),
  seguros_totales numeric(15,2),
  es_analisis_real boolean DEFAULT true,
  validado_por_sistema boolean DEFAULT false,
  datos_manuales_json jsonb,
  updated_at timestamptz
);

CREATE TABLE IF NOT EXISTS propuestas_ahorro (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  analisis_id uuid NOT NULL,
  admin_id uuid,
  tasa_uvr_frech_aplicada numeric(5,2),
  seguros_proyectados numeric(15,2),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS opciones_abono (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  propuesta_id uuid NOT NULL,
  etiqueta varchar(50),
  abono_extra_mensual numeric(15,2),
  nuevas_cuotas_pendientes integer,
  nuevo_tiempo_meses integer,
  ahorro_intereses_total numeric(15,2),
  cuotas_reducidas integer,
  honorarios_estimados numeric(15,2),
  ingresos_minimos_requeridos numeric(15,2)
);

CREATE TABLE IF NOT EXISTS auditoria_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid,
  accion varchar(100),
  ip_address varchar(45),
  detalles jsonb,
  created_at timestamptz DEFAULT now()
);

COMMENT ON COLUMN documentos_s3.s3_key IS 'Path: uploads/{user_id}/{filename}';

-- Foreign keys
ALTER TABLE ciudades
  ADD CONSTRAINT fk_ciudades_departamento
  FOREIGN KEY (departamento_id) REFERENCES departamentos(id);

ALTER TABLE usuarios
  ADD CONSTRAINT fk_usuarios_ciudad
  FOREIGN KEY (ciudad_id) REFERENCES ciudades(id) ON DELETE SET NULL;

ALTER TABLE usuario_roles
  ADD CONSTRAINT fk_usuario_roles_user
  FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE;

ALTER TABLE usuario_roles
  ADD CONSTRAINT fk_usuario_roles_role
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;

ALTER TABLE verificaciones_otp
  ADD CONSTRAINT fk_otp_user
  FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE;

ALTER TABLE documentos_s3
  ADD CONSTRAINT fk_docs_user
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;

ALTER TABLE documentos_s3
  ADD CONSTRAINT fk_docs_banco
  FOREIGN KEY (banco_id) REFERENCES bancos(id) ON DELETE SET NULL;

ALTER TABLE analisis_hipotecario
  ADD CONSTRAINT fk_analisis_documento
  FOREIGN KEY (documento_id) REFERENCES documentos_s3(id) ON DELETE CASCADE;

ALTER TABLE propuestas_ahorro
  ADD CONSTRAINT fk_propuesta_analisis
  FOREIGN KEY (analisis_id) REFERENCES analisis_hipotecario(id) ON DELETE CASCADE;

ALTER TABLE propuestas_ahorro
  ADD CONSTRAINT fk_propuesta_admin
  FOREIGN KEY (admin_id) REFERENCES usuarios(id) ON DELETE SET NULL;

ALTER TABLE opciones_abono
  ADD CONSTRAINT fk_opciones_propuesta
  FOREIGN KEY (propuesta_id) REFERENCES propuestas_ahorro(id) ON DELETE CASCADE;

ALTER TABLE auditoria_logs
  ADD CONSTRAINT fk_auditoria_user
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL;

-- Índices útiles para FKs
CREATE INDEX IF NOT EXISTS idx_ciudades_departamento_id ON ciudades(departamento_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_ciudad_id ON usuarios(ciudad_id);
CREATE INDEX IF NOT EXISTS idx_docs_usuario_id ON documentos_s3(usuario_id);
CREATE INDEX IF NOT EXISTS idx_docs_banco_id ON documentos_s3(banco_id);
CREATE INDEX IF NOT EXISTS idx_analisis_documento_id ON analisis_hipotecario(documento_id);
CREATE INDEX IF NOT EXISTS idx_propuesta_analisis_id ON propuestas_ahorro(analisis_id);
CREATE INDEX IF NOT EXISTS idx_opciones_propuesta_id ON opciones_abono(propuesta_id);

-- (Opcional pero recomendado) índice para consultar OTPs activas rápido
CREATE INDEX IF NOT EXISTS idx_otp_user_tipo_status
  ON verificaciones_otp(user_id, tipo, status);

-- ==========================================
-- SECCIÓN DE DATOS INICIALES (SEEDING)
-- ==========================================

-- 1. Insertar departamentos (Los IDs se generan automáticamente como 1, 2, 3...)
INSERT INTO departamentos (nombre) VALUES
('Atlántico'),
('Bogotá D.C.'),
('Antioquia');

-- 2. Insertar ciudades vinculadas a los IDs anteriores
INSERT INTO ciudades (departamento_id, nombre) VALUES
(1, 'Barranquilla'),
(2, 'Bogotá'),
(3, 'Medellín');

-- 3. Insertar roles para el sistema
INSERT INTO roles (code, name) VALUES
('ADMIN', 'Administrador'),
('CLIENT', 'Cliente');
