-- ==========================================
-- 1. EXTENSIONES Y TABLAS BASE
-- ==========================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tabla para almacenar indicadores de Colombia (UVR, IPC, DTF)
CREATE TABLE IF NOT EXISTS indicadores_economicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) UNIQUE NOT NULL, -- 'UVR', 'IPC', 'DTF'
    valor numeric(15,6) NOT NULL,
    unidad varchar(20), -- 'COP', 'Porcentaje'
    fuente varchar(100), -- 'BanRep', 'DANE'
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS departamentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ciudades (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departamento_id integer NOT NULL,
    nombre varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS bancos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) UNIQUE
);

-- ==========================================
-- 2. USUARIOS Y SISTEMA RBAC
-- ==========================================
CREATE TABLE IF NOT EXISTS usuarios (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    nombres varchar(150),
    primer_apellido varchar(80),
    segundo_apellido varchar(80),
    tipo_identificacion varchar(10),
    identificacion varchar(30) UNIQUE,
    email varchar(255) UNIQUE,
    telefono varchar(30),
    genero varchar(20),
    password_hash varchar(255),
    ciudad_id integer,
    status varchar(20) DEFAULT 'PENDING',
    email_verificado boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roles (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code varchar(30) UNIQUE,
    name varchar(80)
);

CREATE TABLE IF NOT EXISTS permisos (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code varchar(50) UNIQUE,
    descripcion varchar(150)
);

CREATE TABLE IF NOT EXISTS usuario_roles (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS rol_permisos (
    role_id uuid NOT NULL,
    permiso_id uuid NOT NULL,
    PRIMARY KEY (role_id, permiso_id)
);

-- ==========================================
-- 2.1 VERIFICACIONES OTP (Email/SMS)
-- ==========================================
CREATE TABLE IF NOT EXISTS verificaciones_otp (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    code_hash varchar(255),
    tipo varchar(20),  -- EMAIL, SMS
    status varchar(20) DEFAULT 'PENDING',  -- PENDING, VERIFIED, EXPIRED
    expires_at timestamptz,
    used_at timestamptz
);

-- ==========================================
-- 3. DOCUMENTOS Y ANÁLISIS HIPOTECARIO
-- ==========================================
CREATE TABLE IF NOT EXISTS documentos_s3 (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id uuid NOT NULL,
    banco_id integer,
    s3_key text,
    original_filename varchar(255),
    file_size bigint,
    mime_type varchar(50),
    pdf_encrypted boolean DEFAULT false,
    checksum_sha256 varchar(64),
    status varchar(20) DEFAULT 'UPLOADED',
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS analisis_hipotecario (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    documento_id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    
    -- --- Datos proporcionados por el usuario ---
    ingresos_mensuales numeric(15,2),
    capacidad_pago_max numeric(15,2),
    tipo_contrato_laboral varchar(80),
    
    -- --- Datos básicos del crédito (Extraídos del PDF) ---
    nombre_titular_extracto varchar(200),
    numero_credito varchar(50),
    banco_id integer,
    sistema_amortizacion varchar(20),  -- UVR, PESOS
    plan_credito varchar(100),
    valor_prestado_inicial numeric(15,2),
    fecha_desembolso date,
    fecha_extracto date,
    plazo_total_meses integer,
    
    -- --- Estado del crédito (Cuotas) ---
    cuotas_pactadas integer,
    cuotas_pagadas integer,
    cuotas_pendientes integer,
    cuotas_vencidas integer DEFAULT 0,
    
    -- --- Tasas de interés (Efectiva Anual) ---
    tasa_interes_pactada_ea numeric(6,4),
    tasa_interes_cobrada_ea numeric(6,4),
    tasa_interes_subsidiada_ea numeric(6,4),
    tasa_mora_pactada_ea numeric(6,4),
    
    -- --- Montos en pesos ---
    valor_cuota_sin_seguros numeric(15,2),
    valor_cuota_con_seguros numeric(15,2),
    beneficio_frech_mensual numeric(15,2),
    valor_cuota_con_subsidio numeric(15,2),
    saldo_capital_pesos numeric(15,2),
    total_por_pagar numeric(15,2),
    
    -- --- Datos UVR (Si aplica) ---
    saldo_capital_uvr numeric(15,4),
    valor_uvr_fecha_extracto numeric(10,4),
    valor_cuota_uvr numeric(12,4),
    
    -- --- Seguros mensuales ---
    seguro_vida numeric(12,2),
    seguro_incendio numeric(12,2),
    seguro_terremoto numeric(12,2),
    seguros_total_mensual numeric(12,2),
    
    -- --- Cálculos derivados (Para el Resumen) ---
    total_pagado_fecha numeric(15,2),
    total_frech_recibido numeric(15,2),
    monto_real_pagado_banco numeric(15,2),
    ajuste_inflacion_pesos numeric(15,2),
    porcentaje_ajuste_inflacion numeric(6,4),
    total_intereses_seguros numeric(15,2),
    
    -- --- MEJORA 2: Preferencias de abono del usuario ---
    opciones_abono_preferidas jsonb,  -- Ej: [200000, 300000, 400000]
    abono_adicional_actual numeric(15,2),  -- MEJORA 3: Siempre NULL en diagnóstico inicial
    
    -- --- Validaciones y estado ---
    nombre_coincide boolean,
    cedula_coincide boolean,  -- MEJORA 4: Validación de cédula
    identificacion_extracto varchar(20),  -- MEJORA 4: Cédula extraída del PDF
    tipo_documento_detectado varchar(100),  -- MEJORA 1: Tipo de documento si no es hipotecario
    es_extracto_hipotecario boolean DEFAULT true,
    status varchar(30) DEFAULT 'PENDING_EXTRACTION',  -- Incluye: ID_MISMATCH, INVALID_DOCUMENT
    campos_manuales jsonb,
    campos_extraidos_ia jsonb,  -- MEJORA 5: Campos extraídos (readonly)
    datos_raw_gemini jsonb,
    
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz
);

-- Índices para analisis_hipotecario
CREATE INDEX IF NOT EXISTS ix_analisis_numero_credito ON analisis_hipotecario(numero_credito);
CREATE INDEX IF NOT EXISTS ix_analisis_fecha_extracto ON analisis_hipotecario(fecha_extracto);
CREATE INDEX IF NOT EXISTS ix_analisis_status ON analisis_hipotecario(status);
CREATE INDEX IF NOT EXISTS ix_analisis_usuario_id ON analisis_hipotecario(usuario_id);

-- ==========================================
-- 3.1 PROPUESTAS DE AHORRO
-- ==========================================
CREATE TABLE IF NOT EXISTS propuestas_ahorro (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    analisis_id uuid NOT NULL,
    
    -- Identificación de la opción
    numero_opcion integer NOT NULL,
    nombre_opcion varchar(50),
    
    -- Datos de entrada
    abono_adicional_mensual numeric(15,2) NOT NULL,
    
    -- Resultados calculados - Tiempo
    cuotas_nuevas integer,
    tiempo_restante_anios integer,
    tiempo_restante_meses integer,
    cuotas_reducidas integer,
    tiempo_ahorrado_anios integer,
    tiempo_ahorrado_meses integer,
    
    -- Resultados calculados - Dinero
    nuevo_valor_cuota numeric(15,2),
    total_por_pagar_aprox numeric(15,2),
    valor_ahorrado_intereses numeric(15,2),
    veces_pagado numeric(5,2),
    
    -- Honorarios y requisitos
    honorarios_calculados numeric(15,2),
    honorarios_con_iva numeric(15,2),
    ingreso_minimo_requerido numeric(15,2),
    
    -- Metadata
    origen varchar(20) DEFAULT 'USER',  -- USER, ADMIN
    es_opcion_seleccionada boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- Índice para propuestas_ahorro
CREATE INDEX IF NOT EXISTS ix_propuesta_analisis_opcion ON propuestas_ahorro(analisis_id, numero_opcion);

-- ==========================================
-- 3.2 REFERENCIAS PERSONALES DEL USUARIO
-- ==========================================
CREATE TABLE IF NOT EXISTS referencias_usuario (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id uuid NOT NULL,
    
    -- Tipo de referencia: FAMILIAR, PERSONAL
    tipo_referencia varchar(20) NOT NULL,
    
    -- Datos de la referencia
    nombre_completo varchar(200) NOT NULL,
    celular varchar(20) NOT NULL,
    parentesco varchar(50),  -- Solo para FAMILIAR: Padre, Madre, Hermano, etc.
    
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz
);

-- Índice para referencias
CREATE INDEX IF NOT EXISTS ix_referencias_usuario ON referencias_usuario(usuario_id);

-- ==========================================
-- 4. CONSTRAINTS (FKs)
-- ==========================================
ALTER TABLE ciudades ADD CONSTRAINT fk_ciudades_departamento FOREIGN KEY (departamento_id) REFERENCES departamentos(id);
ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudades(id) ON DELETE SET NULL;
ALTER TABLE usuario_roles ADD CONSTRAINT fk_usuario_roles_user FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE usuario_roles ADD CONSTRAINT fk_usuario_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE rol_permisos ADD CONSTRAINT fk_rol_permisos_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE rol_permisos ADD CONSTRAINT fk_rol_permisos_permiso FOREIGN KEY (permiso_id) REFERENCES permisos(id) ON DELETE CASCADE;
ALTER TABLE verificaciones_otp ADD CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE documentos_s3 ADD CONSTRAINT fk_docs_user FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE documentos_s3 ADD CONSTRAINT fk_docs_banco FOREIGN KEY (banco_id) REFERENCES bancos(id) ON DELETE SET NULL;
ALTER TABLE analisis_hipotecario ADD CONSTRAINT fk_analisis_documento FOREIGN KEY (documento_id) REFERENCES documentos_s3(id) ON DELETE CASCADE;
ALTER TABLE analisis_hipotecario ADD CONSTRAINT fk_analisis_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE analisis_hipotecario ADD CONSTRAINT fk_analisis_banco FOREIGN KEY (banco_id) REFERENCES bancos(id) ON DELETE SET NULL;
ALTER TABLE propuestas_ahorro ADD CONSTRAINT fk_propuesta_analisis FOREIGN KEY (analisis_id) REFERENCES analisis_hipotecario(id) ON DELETE CASCADE;
ALTER TABLE referencias_usuario ADD CONSTRAINT fk_referencias_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;

-- ==========================================
-- 5. SEEDING (DATOS INICIALES)
-- ==========================================

-- Indicadores Iniciales (Valores base para evitar errores en frío)
INSERT INTO indicadores_economicos (nombre, valor, unidad, fuente) VALUES 
('UVR', 376.1794, 'COP', 'BanRep'),
('IPC', 0.0, 'Porcentaje', 'DANE')
ON CONFLICT (nombre) DO NOTHING;

-- Departamentos y Ciudades
INSERT INTO departamentos (nombre) VALUES ('Atlántico'), ('Bogotá D.C.'), ('Antioquia');
INSERT INTO ciudades (departamento_id, nombre) VALUES (1, 'Barranquilla'), (2, 'Bogotá'), (3, 'Medellín');

-- Roles
INSERT INTO roles (code, name) VALUES ('ADMIN', 'Administrador'), ('CLIENT', 'Cliente') ON CONFLICT (code) DO NOTHING;

-- Bancos
INSERT INTO bancos (nombre) VALUES 
('Bancolombia'), ('Davivienda'), ('BBVA'), ('Banco de Bogotá'), 
('Scotiabank Colpatria'), ('Banco Caja Social'), ('AV Villas'), 
('Banco de Occidente'), ('Bancoomeva'), ('Banco Popular'), 
('Banco Agrario'), ('Itaú'), ('Finandina'), ('Santander'), 
('Serfinanza'), ('Banco W'), ('Pichincha'), ('Mibanco')
ON CONFLICT (nombre) DO NOTHING;

-- Permisos
INSERT INTO permisos (code, descripcion) VALUES 
('analisis:subir', 'Subir PDFs'),
('analisis:ver_propio', 'Ver resultados propios'),
('admin:ver_todo', 'Acceso total');

-- Asignación de Permisos
INSERT INTO rol_permisos (role_id, permiso_id)
SELECT r.id, p.id FROM roles r, permisos p 
WHERE (r.code = 'CLIENT' AND p.code IN ('analisis:subir', 'analisis:ver_propio'))
   OR (r.code = 'ADMIN')
ON CONFLICT DO NOTHING;