-- ==========================================
-- 1. EXTENSIONES Y TABLAS BASE
-- ==========================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS departamentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ciudades (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  departamento_id integer NOT NULL,
  nombre varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nombres varchar(150),
  primer_apellido varchar(80),
  segundo_apellido varchar(80),
  tipo_identificacion varchar(10),
  identificacion varchar(30) UNIQUE,
  email varchar(255) UNIQUE,
  telefono varchar(30),
  genero varchar(20),
  password_hash varchar(255),
  ciudad_id integer,
  status varchar(20) DEFAULT 'PENDING',
  email_verificado boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- ==========================================
-- 2. SISTEMA RBAC (ROLES Y PERMISOS)
-- ==========================================
CREATE TABLE IF NOT EXISTS roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code varchar(30) UNIQUE,
  name varchar(80)
);

CREATE TABLE IF NOT EXISTS permisos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code varchar(50) UNIQUE, -- Ej: 'credito:subir', 'admin:ver_todo'
  descripcion varchar(150)
);

CREATE TABLE IF NOT EXISTS usuario_roles (
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS rol_permisos (
  role_id uuid NOT NULL,
  permiso_id uuid NOT NULL,
  PRIMARY KEY (role_id, permiso_id)
);

-- ==========================================
-- 3. DOCUMENTOS Y ANÁLISIS
-- ==========================================
CREATE TABLE IF NOT EXISTS verificaciones_otp (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  code_hash varchar(255),
  tipo varchar(20),
  status varchar(20) DEFAULT 'PENDING',
  expires_at timestamptz,
  used_at timestamptz
);

CREATE TABLE IF NOT EXISTS bancos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS documentos_s3 (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  banco_id integer,
  s3_key text,
  original_filename varchar(255),
  file_size bigint,
  mime_type varchar(50),
  pdf_encrypted boolean DEFAULT false,
  checksum_sha256 varchar(64),
  status varchar(20) DEFAULT 'UPLOADED',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS analisis_hipotecario (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  documento_id uuid NOT NULL,
  ingresos_mensuales numeric(15,2),
  capacidad_pago_max numeric(15,2),
  tipo_contrato_laboral varchar(80),
  numero_credito varchar(50),
  sistema_amortizacion varchar(20),
  valor_prestado_inicial numeric(15,2),
  fecha_desembolso date,
  cuotas_pactadas integer,
  cuotas_pagadas integer,
  cuotas_pendientes integer,
  valor_cuota_actual numeric(15,2),
  beneficio_frech_mensual numeric(15,2),
  saldo_capital_hoy numeric(15,2),
  ajuste_inflacion_pesos numeric(15,2),
  intereses_mes_actual numeric(15,2),
  seguros_totales numeric(15,2),
  es_analisis_real boolean DEFAULT true,
  validado_por_sistema boolean DEFAULT false,
  datos_manuales_json jsonb,
  updated_at timestamptz
);

-- (Omití las tablas de propuestas_ahorro y auditoria por brevedad, pero deben ir aquí)

-- ==========================================
-- 4. CONSTRAINTS (FKs)
-- ==========================================
ALTER TABLE ciudades ADD CONSTRAINT fk_ciudades_departamento FOREIGN KEY (departamento_id) REFERENCES departamentos(id);
ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudades(id) ON DELETE SET NULL;
ALTER TABLE usuario_roles ADD CONSTRAINT fk_usuario_roles_user FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE usuario_roles ADD CONSTRAINT fk_usuario_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE rol_permisos ADD CONSTRAINT fk_rol_permisos_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE rol_permisos ADD CONSTRAINT fk_rol_permisos_permiso FOREIGN KEY (permiso_id) REFERENCES permisos(id) ON DELETE CASCADE;
ALTER TABLE verificaciones_otp ADD CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE documentos_s3 ADD CONSTRAINT fk_docs_user FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE documentos_s3 ADD CONSTRAINT fk_docs_banco FOREIGN KEY (banco_id) REFERENCES bancos(id) ON DELETE SET NULL;
ALTER TABLE analisis_hipotecario ADD CONSTRAINT fk_analisis_documento FOREIGN KEY (documento_id) REFERENCES documentos_s3(id) ON DELETE CASCADE;

-- ==========================================
-- 5. DATOS INICIALES (SEEDING) - ¡IMPORTANTE!
-- ==========================================

-- Departamentos y Ciudades
INSERT INTO departamentos (nombre) VALUES ('Atlántico'), ('Bogotá D.C.'), ('Antioquia') ON CONFLICT DO NOTHING;
INSERT INTO ciudades (departamento_id, nombre) VALUES (1, 'Barranquilla'), (2, 'Bogotá'), (3, 'Medellín') ON CONFLICT DO NOTHING;

-- Roles
INSERT INTO roles (code, name) VALUES 
('ADMIN', 'Administrador del Sistema'),
('CLIENT', 'Cliente') 
ON CONFLICT (code) DO NOTHING;

-- Bancos Colombianos (Los 18 solicitados)
INSERT INTO bancos (nombre) VALUES 
('Bancolombia'), ('Davivienda'), ('BBVA'), ('Banco de Bogotá'), 
('Scotiabank Colpatria'), ('Banco Caja Social'), ('AV Villas'), 
('Banco de Occidente'), ('Bancoomeva'), ('Banco Popular'), 
('Banco Agrario'), ('Itaú'), ('Finandina'), ('Santander'), 
('Serfinanza'), ('Banco W'), ('Pichincha'), ('Mibanco')
ON CONFLICT (nombre) DO NOTHING;

-- Permisos
INSERT INTO permisos (code, descripcion) VALUES 
('analisis:subir', 'Permite subir PDFs para análisis'),
('analisis:ver_propio', 'Permite ver sus propios resultados'),
('analisis:ver_todo', 'Permite ver análisis de todos los usuarios'),
('simulacion:recalcular', 'Permite realizar cálculos de ahorro')
ON CONFLICT (code) DO NOTHING;

-- Asociación Permisos a Roles (Asumiendo que CLIENT tiene los 2 primeros y ADMIN tiene todos)
-- Nota: En un script real, usaríamos subconsultas para obtener los IDs de UUIDs recién creados.
INSERT INTO rol_permisos (role_id, permiso_id)
SELECT r.id, p.id FROM roles r, permisos p 
WHERE (r.code = 'CLIENT' AND p.code IN ('analisis:subir', 'analisis:ver_propio'))
   OR (r.code = 'ADMIN')
ON CONFLICT DO NOTHING;